spring:
  flyway:
    enabled: true
    locations: classpath:/db
  datasource:
    url: jdbc:postgresql://localhost:5432/pricetest
    username: sa
    password: 12345
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update